default:
  image: node:18.4.0-alpine

stages:
  - install
  - test
  - build
  - deploy

install-deps-job:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - "node_modules"

lint-test-job:
  stage: test
  script:
    - npm run lint
  dependencies:
    - install-deps-job

unit-test-job:
  stage: test
  script:
    - npm run test
  dependencies:
    - install-deps-job

build-job:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - "dist"
  dependencies:
    - install-deps-job

deploy-npm:
  stage: deploy
  script:
    - echo _auth=$NPMRC_PUBLISH_KEY >> .npmrc
    - echo email=$NPMRC_EMAIL >> .npmrc
    - echo always-auth=true >> .npmrc
    - npm publish
  dependencies:
    - build-job
