default:
  image: node:18.4.0

stages:
  - install
  - test
  - build
  - deploy

install-deps-job:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - "node_modules"

lint-test-job:
  stage: test
  script:
    - npm run lint
  dependencies:
    - install-deps-job

unit-test-job:
  stage: test
  script:
    - npm run test
  dependencies:
    - install-deps-job

build-job:
  stage: build
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
    - npm run build
  artifacts:
    paths:
      - "dist"
      - ".npmrc"
  dependencies:
    - install-deps-job

deploy-npm:
  stage: deploy
  script:
    - npm publish --access public
  dependencies:
    - build-job
